// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Brampton Smoke Cannabis",
  domain: "www.bramptonsmokecannabis.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "132 Falby Rd Unit B, Brampton, ON L6P 4L9",
  streetAddress: "132 Falby Rd Unit B",
  postalCode: "L6P 4L9",
  phone: "+1 (289) 819-5009",
  phoneIntl: "+12898195009",
  neighborhood: "East Brampton",
  nearbyAreas: ["East Brampton", "Falby Road", "Steeles Avenue East", "Brampton Transit", "Local east Brampton neighbourhoods"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7724674",
  longitude: "-79.6563479",
  hours: ["Open 24 Hours"],
  seoTitle: "Weed Dispensary in Brampton | Brampton Smoke Cannabis",
  metaDescription: "Brampton Smoke Cannabis is open 24 hours at 132 Falby Rd Unit B in Brampton. Adults 19+ can explore flower, pre-rolls, edibles, THC vapes and concentrates.",
  localLandmarks: ["Falby Road", "Steeles Avenue East", "East Brampton"],
  introVariant: "Brampton Smoke Cannabis is the east Brampton walk-in shop at 132 Falby Rd Unit B. Adults 19+ can compare weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Use Unit B on Falby Road, near Steeles Avenue East, when you set directions.",
  neighborhoodDescription: "The shop sits on the Falby Road corridor in east Brampton, in a retail plaza with on-site parking and Brampton Transit access via nearby Steeles Avenue.",
  parkingNote: "Parking is available on-site in the retail plaza lot",
  transitNote: "Accessible via Brampton Transit routes serving nearby Steeles Avenue and local Brampton communities.",
  sectionTitle: "Serving Customers Near Brampton and Nearby Peel Communities"
};
