// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Brampton Smoke Cannabis",
  domain: "bramptonsmokecannabis.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "132 Falby Rd Unit B, Brampton, ON L6P 4L9",
  streetAddress: "132 Falby Rd Unit B",
  postalCode: "L6P 4L9",
  phone: "(905) 226-7966",
  phoneIntl: "+19052267966",
  neighborhood: "Brampton",
  nearbyAreas: ["Brampton", "Queen Street", "Kennedy Road", "Bramalea", "Downtown Brampton", "Peel Region", "Brampton Transit", "Local Brampton neighborhoods"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=132+Falby+Rd+Unit+B,+Brampton,+ON+L6P+4L9",
  mapEmbedUrl: "https://maps.google.com/maps?q=Brampton%20Smoke%20Cannabis%20132%20Falby%20Rd%20Unit%20B%2C%20Brampton%2C%20ON%20L6P%204L9&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7915",
  longitude: "-79.6432",
  hours: ["Open 24 Hours"],
  seoTitle: "Brampton Smoke Cannabis | Weed Dispensary in Brampton",
  metaDescription: "Brampton Smoke Cannabis is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Brampton", "Queen Street", "Kennedy Road"],
  introVariant: "Brampton Smoke Cannabis is a local weed dispensary in Brampton, located at 132 Falby Rd Unit B. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Brampton, a cannabis store in Brampton, or a local weed shop close to Queen Street, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Brampton district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Parking is available on-site in the retail plaza lot",
  transitNote: "Accessible via Brampton Transit routes serving nearby Steeles Avenue and local Brampton communities.",
  sectionTitle: "Serving Customers Near Brampton and Nearby Peel Communities"
};
